// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalPeAPI.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace RentalPeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RentalPeAPI.Combo.Domain.Aggregates.Entities.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("image");

                    b.Property<int>("InstallDays")
                        .HasColumnType("int")
                        .HasColumnName("install_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("provider_id");

                    b.HasKey("Id")
                        .HasName("p_k_combos");

                    b.ToTable("combos", (string)null);
                });

            modelBuilder.Entity("RentalPeAPI.Property.Domain.Aggregates.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("space_id");

                    b.HasKey("Id")
                        .HasName("p_k_services");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("i_x_services_space_id");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("RentalPeAPI.Property.Domain.Aggregates.Space", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AreaM2")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("area_m2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_per_hour");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_spaces");

                    b.ToTable("spaces", (string)null);
                });

            modelBuilder.Entity("RentalPeAPI.Property.Domain.Aggregates.Entities.Service", b =>
                {
                    b.HasOne("RentalPeAPI.Property.Domain.Aggregates.Space", "Space")
                        .WithMany("Services")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spaces_services_space_id");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("RentalPeAPI.Property.Domain.Aggregates.Space", b =>
                {
                    b.OwnsOne("RentalPeAPI.Property.Domain.Aggregates.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<long>("SpaceId")
                                .HasColumnType("bigint")
                                .HasColumnName("space_id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("address");

                            b1.HasKey("SpaceId")
                                .HasName("p_k_space_locations");

                            b1.ToTable("space_locations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SpaceId")
                                .HasConstraintName("f_k_space_locations_spaces_space_id");
                        });

                    b.OwnsOne("RentalPeAPI.Property.Domain.Aggregates.ValueObjects.OwnerId", "OwnerId", b1 =>
                        {
                            b1.Property<long>("SpaceId")
                                .HasColumnType("bigint")
                                .HasColumnName("space_id");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("owner_id");

                            b1.HasKey("SpaceId")
                                .HasName("p_k_space_owners");

                            b1.ToTable("space_owners", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SpaceId")
                                .HasConstraintName("f_k_space_owners_spaces_space_id");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("OwnerId")
                        .IsRequired();
                });

            modelBuilder.Entity("RentalPeAPI.Property.Domain.Aggregates.Space", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
